-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 13:28:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `test`.`Profesor` (
  `idProfesor` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(30) NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `test`.`Estudiante` (
  `idEstudiante` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(30) NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `test`.`Asignatura` (
  `idAsignatura` VARCHAR(30) NOT NULL,
  `Profesor_idProfesor` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idAsignatura`),
  INDEX `fk_Asignatura_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `test`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaXEstudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`NotaXEstudiante` ;

CREATE TABLE IF NOT EXISTS `test`.`NotaXEstudiante` (
  `Estudiante_idEstudiante` VARCHAR(30) NOT NULL,
  `Asignatura_idAsignatura` VARCHAR(30) NOT NULL,
  `nota` DOUBLE NULL,
  PRIMARY KEY (`Estudiante_idEstudiante`, `Asignatura_idAsignatura`),
  INDEX `fk_Estudiante_has_Asignatura_Asignatura1_idx` (`Asignatura_idAsignatura` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Asignatura_Estudiante_idx` (`Estudiante_idEstudiante` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Asignatura_Estudiante`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `test`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Asignatura_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `test`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
